### ISSUE TITLE
Single Sign On Support

### ISSUE THREAD

**Issue by simonireilly** [Theodo-UK/sls-dev-tools#679]
**Twitter Handle:**
*(if you'd like a shoutout when we add the feature)*

I use AWS Single Sign On (SSO) and would like to use the sls-dev-tools with transparent sign on.

### Example

```bash
sls-dev-tools --profile dev
```

```toml
# ~/.aws/config
[profile dev]
sso_start_url = "https://my-sso-portal.awsapps.com/start"
sso_region = "us-east-1"
sso_account_id = "123456789011"
sso_role_name = "Developer"
region = "us-west-2"
output = "json"
```

The sls-dev-tools would handle this by signing in and attaining the temporary credentials for the SSO role in the associated account.
